version: "3"
services:
  rail:
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ".:/usr/local/src"
    restart: always
    depends_on:
      - db
    environment:
      - DEFAULT_LIBRARIAN_PASSWORD=password123
      - DATABASE_USERNAME=psql
      - DATABASE_DATABASE=psql
      - DATABASE_PASSWORD=psql
      - DATABASE_HOST=db
    env_file:
      - .env
  db:
    image: postgres:16.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=psql
      - POSTGRES_USER=psql
      - POSTGRES_DB=psql
    volumes:
      - "./data:/var/lib/postgresql/data"
